name: Build Eleventy

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20']

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies & build
        run: |
            npm ci
            npm run build

      - name: Deploy
        uses: peaciris/actions-gh-pages@4
        with:
            publish_dir: ./dist
            github_token: ${{ secrets.GITHUB_TOKEN }} 
